#pragma config(Sensor, S4,     eyes,           sensorEV3_Color)
#pragma config(Motor,  motorA,          motor1,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          motor2,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          motor3,        tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// The first argument is a datalog index number.
	// The filename will be saved in the rc-data folder as
	// datalog-<INDEX>.txt
	// The format is a comma separated value file.
	// The 2nd argument is the number of columns you wish to have in the file
	// The 3rd argument specifies if you wish to append to the datalog, if it
	// exists.
	datalogFlush();
	datalogClose();
	if (!datalogOpen(0, 1, false)){
		displayCenteredTextLine(4,"Unable to open datalog");
	}
	// You can add an entry at the specified column number
for(int i=0;i<2400;i++){
	setMotorSync(motor1, motor2, 0, 5);
  //setMotorSpeed(motor3, 127);

	datalogAddLong(0, getColorReflected(eyes));
	sleep(5);
	//playTone(3000, 1000);

}

	// Make sure you close the file properly
	datalogClose();
}
